'use client';

import React, { useState } from 'react';
import { Sparkles, X, Copy, Check, ShieldAlert, AlertTriangle, CheckCircle2, Share2, Loader2 } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  title: string;
  reviewContent: string;
  loading?: boolean;
  provider?: string;
  model?: string;
}

export function AiPrReviewModal({ isOpen, onClose, title, reviewContent, loading, provider, model }: Props) {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(reviewContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <AnimatePresence>
      <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm">
        <motion.div
          initial={{ opacity: 0, scale: 0.95, y: 10 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95, y: 10 }}
          className="bg-[#111216] border border-border/80 rounded-2xl w-full max-w-3xl overflow-hidden shadow-2xl flex flex-col max-h-[85vh]"
        >
          {/* Header */}
          <div className="flex items-center justify-between px-6 py-4 border-b border-border/50 bg-card-bg/90">
            <div className="flex items-center gap-2.5">
              <div className="p-2 rounded-lg bg-accent/15 border border-accent/30 text-accent">
                <Sparkles className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-base font-semibold text-text-primary">Hive AI Code Review</h3>
                <p className="text-xs text-text-muted truncate max-w-md">{title}</p>
              </div>
            </div>

            <button
              onClick={onClose}
              className="p-1.5 text-text-muted hover:text-text-primary rounded-lg hover:bg-secondary/40 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Model info banner */}
          <div className="px-6 py-2 bg-secondary/20 border-b border-border/30 flex items-center justify-between text-[11px] text-text-muted">
            <span>Engineering Intelligence Layer • Static & Security Analysis</span>
            {model && (
              <span className="font-mono text-accent">
                {provider ? `${provider} / ` : ''}{model}
              </span>
            )}
          </div>

          {/* Review Content */}
          <div className="flex-1 overflow-y-auto p-6 space-y-4">
            {loading ? (
              <div className="flex flex-col items-center justify-center py-20 gap-3 text-text-muted text-sm">
                <Loader2 className="w-8 h-8 animate-spin text-accent" />
                <p>Hive AI is analyzing code changes, risks, and edge cases...</p>
              </div>
            ) : (
              <div className="text-sm text-text-secondary leading-relaxed whitespace-pre-wrap font-sans selection:bg-accent/20">
                {reviewContent}
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="flex items-center justify-between px-6 py-3.5 border-t border-border/50 bg-card-bg/60">
            <span className="text-xs text-text-muted">Advisory review generated by Hive AI</span>

            <div className="flex items-center gap-2">
              <button
                onClick={handleCopy}
                disabled={loading || !reviewContent}
                className="flex items-center gap-1.5 px-3.5 py-1.5 text-xs font-medium bg-secondary/60 hover:bg-secondary text-text-primary rounded-lg border border-border/40 transition-colors disabled:opacity-50"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied' : 'Copy Review'}</span>
              </button>

              <button
                onClick={onClose}
                className="px-4 py-1.5 text-xs font-medium bg-accent hover:bg-accent-hover text-white rounded-lg transition-colors"
              >
                Done
              </button>
            </div>
          </div>
        </motion.div>
      </div>
    </AnimatePresence>
  );
}

