// ─── Bangladesh UGC Approved Universities & Institutes ────────────────────────
// Source: University Grants Commission (UGC) of Bangladesh

export const BANGLADESH_UNIVERSITIES = [
  // ─── Top Public Universities ───────────────────────────────────────────────
  'University of Dhaka (DU)',
  'Bangladesh University of Engineering and Technology (BUET)',
  'Jahangirnagar University (JU)',
  'University of Rajshahi (RU)',
  'University of Chittagong (CU)',
  'Shahjalal University of Science and Technology (SUST)',
  'Khulna University (KU)',
  'Bangladesh Agricultural University (BAU)',
  'Bangladesh University of Professionals (BUP)',
  'Jagannath University (JnU)',
  'Islamic University, Bangladesh (IU)',
  'Comilla University (CoU)',
  'Jatiya Kabi Kazi Nazrul Islam University (JKKNIU)',
  'Begum Rokeya University, Rangpur (BRUR)',
  'University of Barishal (BU)',
  'Rabindra University, Bangladesh (RUB)',
  'Sheikh Hasina University (SHU)',
  'Bangabandhu Sheikh Mujibur Rahman Digital University (BDU)',
  'Bangabandhu Sheikh Mujibur Rahman Aviation and Aerospace University (BSMRAAU)',
  'Bangamata Sheikh Fojilatunnesa Mujib Science & Technology University (BSFMSTU)',
  'Chandpur Science and Technology University (CSTU)',
  'Sunamganj Science and Technology University (SSTU)',
  'Bogura Science and Technology University (BSTU)',
  'Lakshmipur Science and Technology University (LSTU)',
  'Mujibnagar University, Meherpur',

  // ─── Engineering & Technology Universities (Public) ────────────────────────
  'Chittagong University of Engineering & Technology (CUET)',
  'Rajshahi University of Engineering & Technology (RUET)',
  'Khulna University of Engineering & Technology (KUET)',
  'Dhaka University of Engineering & Technology (DUET)',
  'Bangladesh University of Textiles (BUTEX)',
  'Mawlana Bhashani Science and Technology University (MBSTU)',
  'Patuakhali Science and Technology University (PSTU)',
  'Hajee Mohammad Danesh Science & Technology University (HSTU)',
  'Noakhali Science and Technology University (NSTU)',
  'Pabna University of Science and Technology (PUST)',
  'Jessore University of Science and Technology (JUST)',
  'Bangabandhu Sheikh Mujibur Rahman Science & Technology University (BSMRSTU)',
  'Rangamati Science and Technology University (RMSTU)',

  // ─── Agricultural & Specialized Universities ──────────────────────────────
  'Bangabandhu Sheikh Mujibur Rahman Agricultural University (BSMRAU)',
  'Sher-e-Bangla Agricultural University (SAU)',
  'Sylhet Agricultural University (SAU)',
  'Khulna Agricultural University (KAU)',
  'Habiganj Agricultural University (HAU)',
  'Kurigram Agricultural University (KrAU)',
  'Chittagong Veterinary and Animal Sciences University (CVASU)',
  'Bangabandhu Sheikh Mujib Medical University (BSMMU)',
  'Rajshahi Medical University (RMU)',
  'Chittagong Medical University (CMU)',
  'Sylhet Medical University (SMU)',
  'Sheikh Hasina Medical University, Khulna',
  'Bangladesh Open University (BOU)',
  'National University, Bangladesh (NU)',
  'Islamic University of Technology (IUT) - OIC',
  'Asian University for Women (AUW)',

  // ─── Top UGC-Approved Private Universities ─────────────────────────────────
  'North South University (NSU)',
  'BRAC University (BRACU)',
  'Independent University, Bangladesh (IUB)',
  'American International University-Bangladesh (AIUB)',
  'Ahsanullah University of Science and Technology (AUST)',
  'East West University (EWU)',
  'United International University (UIU)',
  'University of Liberal Arts Bangladesh (ULAB)',
  'Daffodil International University (DIU)',
  'International Islamic University Chittagong (IIUC)',
  'Green University of Bangladesh (GUB)',
  'Southeast University (SEU)',
  'University of Asia Pacific (UAP)',
  'Primeasia University',
  'Stamford University Bangladesh',
  'State University of Bangladesh (SUB)',
  'World University of Bangladesh (WUB)',
  'Eastern University',
  'Canadian University of Bangladesh (CUB)',
  'Varendra University (VU)',
  'Premier University, Chittagong (PUC)',
  'Metropolitan University, Sylhet',
  'Leading University, Sylhet',
  'Southern University Bangladesh',
  'East Delta University (EDU)',
  'Port City International University (PCIU)',
  'University of Information Technology and Sciences (UITS)',
  'University of Development Alternative (UODA)',
  'Dhaka International University (DIU-Dhaka)',
  'City University, Bangladesh',
  'Northern University Bangladesh (NUB)',
  'ASA University Bangladesh (ASAUB)',
  'BGC Trust University Bangladesh',
  'Presidency University, Bangladesh',
  'Manarat International University (MIU)',
  'European University of Bangladesh (EUB)',
  'Bangladesh University of Business and Technology (BUBT)',
  'Gono Bishwabidyalay',
  'Hamdard University Bangladesh',
  'Fareast International University',
  'Sonargaon University (SU)',
  'Cox\'s Bazar International University (CBIU)',
  'Ranada Prasad Shaha University (RPSU)',
  'German University Bangladesh (GUB-German)',
  'Global University Bangladesh',
  'Central University of Science and Technology (CUST)',
  'Tagore University of Creative Arts',
  'Z. H. Sikder University of Science & Technology',
  'Feni University',
  'Britannia University',
  'Royal University of Dhaka',
  'BGMEA University of Fashion & Technology (BUFT)',
  'Shanto-Mariam University of Creative Technology',
];

export function searchUniversities(query: string): string[] {
  if (!query || query.trim().length === 0) return BANGLADESH_UNIVERSITIES.slice(0, 8);
  const q = query.toLowerCase().trim();
  return BANGLADESH_UNIVERSITIES.filter((u) => u.toLowerCase().includes(q));
}
